export const PROVIDERS = [
  { kind: "openai", name: "OpenAI", format: "openai", baseUrl: "https://api.openai.com/v1", models: ["gpt-4.1-mini", "gpt-4o-mini"] },
  { kind: "anthropic", name: "Anthropic", format: "anthropic", baseUrl: "https://api.anthropic.com/v1", models: ["claude-sonnet-4-5"] },
  { kind: "google", name: "Google Gemini", format: "gemini", baseUrl: "https://generativelanguage.googleapis.com/v1beta", models: ["gemini-2.5-flash"] },
  { kind: "openrouter", name: "OpenRouter", format: "openai", baseUrl: "https://openrouter.ai/api/v1", models: ["openai/gpt-4o-mini"] },
  { kind: "groq", name: "Groq", format: "openai", baseUrl: "https://api.groq.com/openai/v1", models: ["llama-3.3-70b-versatile"] },
  { kind: "mistral", name: "Mistral", format: "openai", baseUrl: "https://api.mistral.ai/v1", models: ["mistral-small-latest"] },
  { kind: "cohere", name: "Cohere", format: "openai", baseUrl: "https://api.cohere.ai/compatibility/v1", models: ["command-r"] },
  { kind: "deepseek", name: "DeepSeek", format: "openai", baseUrl: "https://api.deepseek.com", models: ["deepseek-chat"] },
  { kind: "perplexity", name: "Perplexity", format: "openai", baseUrl: "https://api.perplexity.ai", models: ["sonar"] },
  { kind: "together", name: "Together AI", format: "openai", baseUrl: "https://api.together.xyz/v1", models: ["meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"] },
  { kind: "fireworks", name: "Fireworks", format: "openai", baseUrl: "https://api.fireworks.ai/inference/v1", models: ["accounts/fireworks/models/llama-v3p1-70b-instruct"] },
  { kind: "xai", name: "xAI", format: "openai", baseUrl: "https://api.x.ai/v1", models: ["grok-4.5"] },
  { kind: "ollama", name: "Ollama", format: "ollama", baseUrl: "http://localhost:11434", models: ["llama3.1"] },
];

export const ACTIONS = [
  ["explain", "Explain"],
  ["summarize", "Summarize"],
  ["rewrite", "Rewrite"],
  ["shorten", "Shorten"],
  ["expand", "Expand"],
  ["simplify", "Simplify"],
  ["pro", "Professionalize"],
  ["casual", "Make casual"],
  ["translate", "Translate"],
  ["grammar", "Fix grammar"],
  ["pov", "Change POV"],
  ["dialogue", "Improve dialogue"],
  ["emotion", "Make more emotional"],
  ["dramatic", "Make more dramatic"],
  ["darker", "Make darker"],
  ["funnier", "Make funnier"],
  ["action", "Improve action"],
  ["romance", "Improve romance/tension"],
  ["continue", "Continue"],
  ["save-note", "Save to notes"],
];

export const PROMPTS = {
  explain: "Explain this clearly:\n\n{{text}}",
  summarize: "Summarize, keep names and numbers:\n\n{{text}}",
  rewrite: "Rewrite more clearly, keep meaning:\n\n{{text}}",
  shorten: "Cut about 40% without losing facts:\n\n{{text}}",
  expand: "Expand with sensory detail. Do not change plot:\n\n{{text}}",
  simplify: "Simplify vocabulary, keep meaning:\n\n{{text}}",
  pro: "Make this professional and direct:\n\n{{text}}",
  casual: "Make this casual:\n\n{{text}}",
  translate: "Translate into English (or the language named if present):\n\n{{text}}",
  grammar: "Fix grammar and spelling only:\n\n{{text}}",
  pov: "Rewrite in close third person, keep events:\n\n{{text}}",
  dialogue: "Improve dialogue. Keep character voice:\n\n{{text}}",
  emotion: "Heighten emotion without melodrama:\n\n{{text}}",
  dramatic: "Increase dramatic pressure. No extra plot twists:\n\n{{text}}",
  darker: "Shift darker in imagery and consequence:\n\n{{text}}",
  funnier: "Add dry, character-true humor:\n\n{{text}}",
  action: "Clarify blocking and impact:\n\n{{text}}",
  romance: "Increase interpersonal tension. Stay in character:\n\n{{text}}",
  continue: "Continue in the same voice for 400-800 words:\n\n{{text}}",
};
